package com.tss.loan.entity.enums;

public enum ApiEndpointType {
    DEFAULTER_CHECK,
    PAN_VERIFICATION,
    AADHAAR_VERIFICATION,
    CREDIT_BUREAU_CHECK,
    EMPLOYMENT_VERIFICATION,
    BANK_VERIFICATION,
    FRAUD_DATABASE_CHECK,
    IDENTITY_VERIFICATION,
    ADDRESS_VERIFICATION,
    PHONE_VERIFICATION,
    EMAIL_VERIFICATION
}
