package com.tss.loan.entity.enums;

public enum ApplicationStatus {
    DRAFT,
    SUBMITTED,
    DOCUMENT_VERIFICATION,
    DOCUMENT_INCOMPLETE,
    FINANCIAL_REVIEW,
    CREDIT_CHECK,
    EMPLOYMENT_VERIFICATION,
    RISK_ASSESSMENT,
    FRAUD_CHECK,
    COLLATERAL_VERIFICATION,
    UNDER_REVIEW,
    COMPLIANCE_REVIEW,
    MANAGER_APPROVAL,
    PRE_APPROVED,
    APPROVED,
    REJECTED,
    DOCUMENTATION,
    DISBURSEMENT_PENDING,
    DISBURSED,
    ON_HOLD,
    CANCELLED,
    EXPIRED
}
