package com.tss.loan.entity.enums;

public enum DecisionType {
    APPROVED,
    REJECTED,
    PENDING,
    AUTO_APPROVED,
    AUTO_REJECTED,
    MANUAL_APPROVED,
    MANUAL_REJECTED,
    ESCALATED,
    PENDING_INVESTIGATION,
    CONDITIONAL_APPROVAL,
    DEFERRED,
    CANCELLED_BY_APPLICANT,
    EXPIRED
}
