package com.tss.loan.entity.enums;

public enum FraudTagType {
    DEFAULTER,
    MULTIPLE_APPLICATIONS,
    IDENTITY_MISMATCH,
    DOCUMENT_FRAUD,
    INCOME_INFLATION,
    EMPLOYMENT_FRAUD,
    ADDRESS_MISMATCH,
    PHONE_FRAUD,
    EMAIL_FRAUD,
    CREDIT_HISTORY_MANIPULATION,
    SUSPICIOUS_TRANSACTION_PATTERN,
    BLACKLISTED_ENTITY,
    HIGH_RISK_LOCATION,
    DUPLICATE_DOCUMENTS,
    SYNTHETIC_IDENTITY
}
