package com.tss.loan.entity.enums;

public enum BusinessEventType {
    // User & Authentication Events
    USER_REGISTERED,
    EMAIL_VERIFICATION_REQUESTED,
    PASSWORD_RESET_REQUESTED,
    ACCOUNT_ACTIVATED,
    PASSWORD_CHANGED,
    PROFILE_UPDATED,
    LOGIN_FROM_NEW_DEVICE,
    SUSPICIOUS_ACTIVITY_DETECTED,
    
    // Application Lifecycle Events
    APPLICATION_CREATED,
    APPLICATION_SUBMITTED,
    APPLICATION_UNDER_REVIEW,
    APPLICATION_READY_FOR_DECISION,
    APPLICATION_APPROVED,
    APPLICATION_REJECTED,
    APPLICATION_EXPIRED,
    APPLICATION_CANCELLED,
    
    // Document Events
    DOCUMENT_UPLOADED,
    DOCUMENT_VERIFIED,
    DOCUMENT_REJECTED,
    DOCUMENT_VERIFICATION_COMPLETE,
    DOCUMENT_RESUBMISSION_REQUIRED,
    DOCUMENT_RESUBMISSION_DEADLINE_REMINDER,
    MISSING_DOCUMENTS_ALERT,
    ADDITIONAL_DOCUMENTS_REQUESTED,
    
    // External Verification Events
    EXTERNAL_VERIFICATION_STARTED,
    EXTERNAL_VERIFICATION_COMPLETE,
    
    // Compliance Events
    APPLICATION_FLAGGED_COMPLIANCE,
    COMPLIANCE_INVESTIGATION_STARTED,
    COMPLIANCE_DOCUMENTS_REQUESTED,
    COMPLIANCE_CLEARED,
    COMPLIANCE_REJECTED,
    COMPLIANCE_DEADLINE_WARNING,
    COMPLIANCE_REVIEW_COMPLETED,
    
    // Officer Assignment Events
    NEW_ASSIGNMENT,
    URGENT_ASSIGNMENT,
    APPLICATION_REASSIGNED,
    DOCUMENTS_RESUBMITTED,
    APPLICATION_DEADLINE_APPROACHING,
    
    // Communication Events
    NEW_COMMENT_ON_APPLICATION,
    OFFICER_REPLIED_TO_QUERY,
    
    // Admin Events
    OFFICER_ACCOUNT_CREATED,
    ROLE_PERMISSIONS_CHANGED,
    SYSTEM_MAINTENANCE_SCHEDULED,
    ACCOUNT_LOCKED,
    POLICY_UPDATE,
    
    // Security & System Events
    SECURITY_ALERT,
    CRITICAL_SYSTEM_EVENT
}


