package com.tss.loan.entity.enums;

public enum DocumentType {
    // Identity documents
    AADHAAR_CARD,
    PAN_CARD,
    PASSPORT,
    VOTER_ID,
    DRIVING_LICENSE,
    
    // Address proof
    UTILITY_BILL,
    BANK_STATEMENT_ADDRESS,
    RENTAL_AGREEMENT,
    PROPERTY_TAX_RECEIPT,
    
    // Income documents
    SALARY_SLIP,
    BANK_STATEMENT,
    ITR_FORM,
    FORM_16,
    EMPLOYMENT_CERTIFICATE,
    APPOINTMENT_LETTER,
    
    // Business documents
    BUSINESS_REGISTRATION,
    GST_CERTIFICATE,
    BUSINESS_BANK_STATEMENT,
    PROFIT_LOSS_STATEMENT,
    BALANCE_SHEET,
    BUSINESS_ITR,
    FINANCIAL_STATEMENT,
    
    // Property documents
    PROPERTY_PAPERS,
    PROPERTY_VALUATION,
    PROPERTY_TAX_DOCUMENT,
    ENCUMBRANCE_CERTIFICATE,
    SURVEY_SETTLEMENT,
    
    // Collateral documents
    GOLD_APPRAISAL,
    VEHICLE_RC,
    VEHICLE_INSURANCE,
    FD_CERTIFICATE,
    SHARE_CERTIFICATE,
    
    // Co-applicant documents
    CO_APPLICANT_IDENTITY,
    CO_APPLICANT_INCOME,
    CO_APPLICANT_BANK_STATEMENT,
    
    // Other documents
    PHOTOGRAPH,
    SIGNATURE_VERIFICATION,
    LOAN_APPLICATION_FORM,
    PROCESSING_FEE_RECEIPT,
    INSURANCE_DOCUMENTS,
    
    // Digital verification
    DIGITAL_SIGNATURE,
    BIOMETRIC_VERIFICATION,
    VIDEO_KYC
}
