package com.tss.loan.entity.enums;

public enum LoanType {
    PERSONAL_LOAN,
    SALARY_ADVANCE,
    HOME_LOAN,
    PROPERTY_LOAN,
    LOAN_AGAINST_PROPERTY,
    CAR_LOAN,
    TWO_WHEELER_LOAN,
    COMMERCIAL_VEHICLE_LOAN,
    BUSINESS_LOAN,
    WORKING_CAPITAL_LOAN,
    EQUIPMENT_FINANCE,
    CROP_LOAN,
    FARM_EQUIPMENT_LOAN,
    EDUCATION_LOAN,
    PROFESSIONAL_COURSE_LOAN,
    GOLD_LOAN,
    CREDIT_CARD,
    OVERDRAFT_FACILITY
}
